Error in rule blast_search:
    jobid: 0
    output: blast/blast_search_output.tsv

RuleException:
CalledProcessError in line 30 of /home/ashlynn/Desktop/Fall_2019/Brucella/source/suis/blast.smk:
Command ' set -euo pipefail;  blastn -db blast/suis_master.fna -query query_file.fna -dust no -word_size 7 -evalue 100 -outfmt 6 -out blast/blast_search_output.tsv ' returned non-zero exit status 2.
  File "/home/ashlynn/Desktop/Fall_2019/Brucella/source/suis/blast.smk", line 30, in __rule_blast_search
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message
